import {
  Joint,
  Muscle,
  Modality,
  MovementPattern,
  Equipment,
  DifficultyTier,
  LoadType,
} from "../models/index";
import type { Movement } from "../models/index";

/**
 * Seed movement library.
 *
 * Each movement includes full metadata for the constraint engine:
 * - Equipment required
 * - Muscles trained (primary + secondary)
 * - Joints loaded
 * - Movement Patterns
 * - Movement tags for impediment filtering
 * - Substitution chains (easiest -> hardest alternatives)
 */
export const MOVEMENT_LIBRARY: Movement[] = [
  // ─── WEIGHTLIFTING: BARBELL ──────────────────────────────────────
  {
    id: "back_squat",
    name: "Back Squat",
    equipment: [Equipment.Barbell, Equipment.Plates, Equipment.SquatRack],
    primaryMuscles: [Muscle.Quads, Muscle.Glutes],
    secondaryMuscles: [Muscle.Hamstrings, Muscle.Core, Muscle.LowerBack],
    loadedJoints: [Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Squat],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Intermediate,
    tags: ["axial_load"],
    loadType: LoadType.Weighted,
    defaultLoadMale: 225,
    defaultLoadFemale: 155,
    substitutions: ["air_squat", "goblet_squat", "dumbbell_squat", "front_squat"],
  },
  {
    id: "front_squat",
    name: "Front Squat",
    equipment: [Equipment.Barbell, Equipment.Plates, Equipment.SquatRack],
    primaryMuscles: [Muscle.Quads, Muscle.Core],
    secondaryMuscles: [Muscle.Glutes, Muscle.UpperBack],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Squat],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Intermediate,
    tags: ["axial_load"],
    loadType: LoadType.Weighted,
    defaultLoadMale: 185,
    defaultLoadFemale: 125,
    substitutions: ["air_squat", "goblet_squat", "dumbbell_squat"],
  },
  {
    id: "overhead_squat",
    name: "Overhead Squat",
    equipment: [Equipment.Barbell, Equipment.Plates],
    primaryMuscles: [Muscle.Quads, Muscle.Shoulders],
    secondaryMuscles: [Muscle.Core, Muscle.Glutes, Muscle.UpperBack],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Squat],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Advanced,
    tags: ["overhead", "high_skill", "axial_load"],
    loadType: LoadType.Weighted,
    defaultLoadMale: 135,
    defaultLoadFemale: 95,
    substitutions: ["air_squat", "goblet_squat", "front_squat"],
  },
  {
    id: "deadlift",
    name: "Deadlift",
    equipment: [Equipment.Barbell, Equipment.Plates],
    primaryMuscles: [Muscle.Hamstrings, Muscle.Glutes, Muscle.LowerBack],
    secondaryMuscles: [Muscle.Quads, Muscle.Forearms, Muscle.UpperBack],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Hinge],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Intermediate,
    tags: ["axial_load"],
    loadType: LoadType.Weighted,
    defaultLoadMale: 315,
    defaultLoadFemale: 205,
    substitutions: ["kettlebell_deadlift", "dumbbell_deadlift", "sumo_deadlift"],
  },
  {
    id: "sumo_deadlift",
    name: "Sumo Deadlift",
    equipment: [Equipment.Barbell, Equipment.Plates],
    primaryMuscles: [Muscle.Glutes, Muscle.Adductors, Muscle.Hamstrings],
    secondaryMuscles: [Muscle.Quads, Muscle.LowerBack],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Hinge],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Intermediate,
    tags: ["axial_load"],
    loadType: LoadType.Weighted,
    defaultLoadMale: 315,
    defaultLoadFemale: 205,
    substitutions: ["kettlebell_deadlift", "dumbbell_deadlift", "deadlift"],
  },
  {
    id: "sumo_deadlift_high_pull",
    name: "Sumo Deadlift High Pull",
    equipment: [Equipment.Barbell, Equipment.Plates],
    primaryMuscles: [Muscle.Hamstrings, Muscle.Glutes, Muscle.Shoulders],
    secondaryMuscles: [Muscle.UpperBack, Muscle.Biceps, Muscle.Core],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Hinge, MovementPattern.Pull],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Intermediate,
    tags: [],
    loadType: LoadType.Weighted,
    defaultLoadMale: 75,
    defaultLoadFemale: 55,
    substitutions: ["kettlebell_swing", "dumbbell_deadlift"],
  },
  {
    id: "bench_press",
    name: "Bench Press",
    equipment: [Equipment.Barbell, Equipment.Plates, Equipment.Bench],
    primaryMuscles: [Muscle.Chest, Muscle.Triceps],
    secondaryMuscles: [Muscle.Shoulders],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Spine],
    movementPatterns: [MovementPattern.Push],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Intermediate,
    tags: ["supine"],
    loadType: LoadType.Weighted,
    defaultLoadMale: 185,
    defaultLoadFemale: 105,
    substitutions: ["push_up", "dumbbell_bench_press", "floor_press"],
  },
  {
    id: "strict_press",
    name: "Strict Press",
    equipment: [Equipment.Barbell, Equipment.Plates],
    primaryMuscles: [Muscle.Shoulders, Muscle.Triceps],
    secondaryMuscles: [Muscle.Core, Muscle.UpperBack],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Spine],
    movementPatterns: [MovementPattern.Push],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Intermediate,
    tags: ["overhead"],
    loadType: LoadType.Weighted,
    defaultLoadMale: 135,
    defaultLoadFemale: 85,
    substitutions: ["dumbbell_press", "push_press"],
  },
  {
    id: "push_press",
    name: "Push Press",
    equipment: [Equipment.Barbell, Equipment.Plates],
    primaryMuscles: [Muscle.Shoulders, Muscle.Triceps],
    secondaryMuscles: [Muscle.Quads, Muscle.Core],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Push],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Intermediate,
    tags: ["overhead"],
    loadType: LoadType.Weighted,
    defaultLoadMale: 155,
    defaultLoadFemale: 105,
    substitutions: ["dumbbell_press", "strict_press"],
  },
  {
    id: "push_jerk",
    name: "Push Jerk",
    equipment: [Equipment.Barbell, Equipment.Plates],
    primaryMuscles: [Muscle.Shoulders, Muscle.Triceps],
    secondaryMuscles: [Muscle.Quads, Muscle.Core, Muscle.HipFlexors],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Push],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Advanced,
    tags: ["overhead", "high_skill"],
    loadType: LoadType.Weighted,
    defaultLoadMale: 185,
    defaultLoadFemale: 125,
    substitutions: ["dumbbell_press", "strict_press", "push_press"],
  },
  {
    id: "clean",
    name: "Clean",
    equipment: [Equipment.Barbell, Equipment.Plates],
    primaryMuscles: [Muscle.Hamstrings, Muscle.Glutes, Muscle.Quads],
    secondaryMuscles: [Muscle.UpperBack, Muscle.Shoulders, Muscle.Core],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Hinge, MovementPattern.Squat],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Advanced,
    tags: ["high_skill", "complex", "axial_load"],
    loadType: LoadType.Weighted,
    defaultLoadMale: 185,
    defaultLoadFemale: 125,
    substitutions: ["kettlebell_clean", "dumbbell_clean", "hang_clean", "power_clean"],
  },
  {
    id: "power_clean",
    name: "Power Clean",
    equipment: [Equipment.Barbell, Equipment.Plates],
    primaryMuscles: [Muscle.Hamstrings, Muscle.Glutes],
    secondaryMuscles: [Muscle.UpperBack, Muscle.Shoulders, Muscle.Quads],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Hinge],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Advanced,
    tags: ["high_skill", "complex"],
    loadType: LoadType.Weighted,
    defaultLoadMale: 165,
    defaultLoadFemale: 110,
    substitutions: ["kettlebell_clean", "dumbbell_clean", "hang_clean"],
  },
  {
    id: "hang_clean",
    name: "Hang Clean",
    equipment: [Equipment.Barbell, Equipment.Plates],
    primaryMuscles: [Muscle.Hamstrings, Muscle.Glutes],
    secondaryMuscles: [Muscle.UpperBack, Muscle.Shoulders],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Hinge],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Intermediate,
    tags: ["high_skill"],
    loadType: LoadType.Weighted,
    defaultLoadMale: 155,
    defaultLoadFemale: 105,
    substitutions: ["kettlebell_clean", "dumbbell_clean"],
  },
  {
    id: "hang_power_clean",
    name: "Hang Power Clean",
    equipment: [Equipment.Barbell, Equipment.Plates],
    primaryMuscles: [Muscle.Hamstrings, Muscle.Glutes],
    secondaryMuscles: [Muscle.UpperBack, Muscle.Shoulders, Muscle.Quads],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Hinge],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Intermediate,
    tags: ["high_skill"],
    loadType: LoadType.Weighted,
    defaultLoadMale: 155,
    defaultLoadFemale: 105,
    substitutions: ["hang_clean", "power_clean", "dumbbell_clean"],
  },
  {
    id: "snatch",
    name: "Snatch",
    equipment: [Equipment.Barbell, Equipment.Plates],
    primaryMuscles: [Muscle.Shoulders, Muscle.Hamstrings, Muscle.Glutes],
    secondaryMuscles: [Muscle.Core, Muscle.Quads, Muscle.UpperBack],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Hinge, MovementPattern.Push],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Advanced,
    tags: ["overhead", "high_skill", "complex", "axial_load"],
    loadType: LoadType.Weighted,
    defaultLoadMale: 135,
    defaultLoadFemale: 95,
    substitutions: ["dumbbell_snatch", "kettlebell_snatch", "power_snatch", "hang_snatch"],
  },
  {
    id: "power_snatch",
    name: "Power Snatch",
    equipment: [Equipment.Barbell, Equipment.Plates],
    primaryMuscles: [Muscle.Shoulders, Muscle.Hamstrings, Muscle.Glutes],
    secondaryMuscles: [Muscle.Core, Muscle.UpperBack],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Hinge, MovementPattern.Push],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Advanced,
    tags: ["overhead", "high_skill"],
    loadType: LoadType.Weighted,
    defaultLoadMale: 115,
    defaultLoadFemale: 75,
    substitutions: ["dumbbell_snatch", "kettlebell_snatch", "hang_snatch"],
  },
  {
    id: "hang_snatch",
    name: "Hang Snatch",
    equipment: [Equipment.Barbell, Equipment.Plates],
    primaryMuscles: [Muscle.Shoulders, Muscle.Hamstrings],
    secondaryMuscles: [Muscle.Glutes, Muscle.Core],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Hinge, MovementPattern.Push],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Advanced,
    tags: ["overhead", "high_skill"],
    loadType: LoadType.Weighted,
    defaultLoadMale: 115,
    defaultLoadFemale: 75,
    substitutions: ["dumbbell_snatch", "kettlebell_snatch"],
  },
  {
    id: "thruster",
    name: "Thruster",
    equipment: [Equipment.Barbell, Equipment.Plates],
    primaryMuscles: [Muscle.Quads, Muscle.Shoulders],
    secondaryMuscles: [Muscle.Glutes, Muscle.Core, Muscle.Triceps],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Squat, MovementPattern.Push],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Intermediate,
    tags: ["overhead"],
    loadType: LoadType.Weighted,
    defaultLoadMale: 95,
    defaultLoadFemale: 65,
    substitutions: ["dumbbell_thruster", "kettlebell_thruster", "air_squat"],
  },
  {
    id: "clean_and_jerk",
    name: "Clean & Jerk",
    equipment: [Equipment.Barbell, Equipment.Plates],
    primaryMuscles: [Muscle.Hamstrings, Muscle.Glutes, Muscle.Shoulders],
    secondaryMuscles: [Muscle.Quads, Muscle.Core, Muscle.UpperBack],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Hinge, MovementPattern.Squat, MovementPattern.Push],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Advanced,
    tags: ["overhead", "high_skill", "complex", "axial_load"],
    loadType: LoadType.Weighted,
    defaultLoadMale: 185,
    defaultLoadFemale: 125,
    substitutions: ["dumbbell_clean", "kettlebell_clean", "hang_clean", "power_clean"],
  },

  // ─── WEIGHTLIFTING: DUMBBELL / KETTLEBELL ────────────────────────
  {
    id: "goblet_squat",
    name: "Goblet Squat",
    equipment: [Equipment.Dumbbell],
    primaryMuscles: [Muscle.Quads, Muscle.Glutes],
    secondaryMuscles: [Muscle.Core],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Squat],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Beginner,
    tags: [],
    loadType: LoadType.Weighted,
    defaultLoadMale: 50,
    defaultLoadFemale: 35,
    substitutions: ["air_squat"],
  },
  {
    id: "dumbbell_squat",
    name: "Dumbbell Squat",
    equipment: [Equipment.Dumbbell],
    primaryMuscles: [Muscle.Quads, Muscle.Glutes],
    secondaryMuscles: [Muscle.Hamstrings, Muscle.Core],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Squat],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Beginner,
    tags: [],
    loadType: LoadType.Weighted,
    defaultLoadMale: 50,
    defaultLoadFemale: 35,
    substitutions: ["air_squat", "goblet_squat"],
  },
  {
    id: "dumbbell_press",
    name: "Dumbbell Press",
    equipment: [Equipment.Dumbbell],
    primaryMuscles: [Muscle.Shoulders, Muscle.Triceps],
    secondaryMuscles: [Muscle.Core],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Spine],
    movementPatterns: [MovementPattern.Push],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Beginner,
    tags: ["overhead"],
    loadType: LoadType.Weighted,
    defaultLoadMale: 50,
    defaultLoadFemale: 35,
    substitutions: ["push_up"],
  },
  {
    id: "dumbbell_bench_press",
    name: "Dumbbell Bench Press",
    equipment: [Equipment.Dumbbell, Equipment.Bench],
    primaryMuscles: [Muscle.Chest, Muscle.Triceps],
    secondaryMuscles: [Muscle.Shoulders],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Spine],
    movementPatterns: [MovementPattern.Push],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Beginner,
    tags: ["supine"],
    loadType: LoadType.Weighted,
    defaultLoadMale: 50,
    defaultLoadFemale: 30,
    substitutions: ["push_up", "floor_press"],
  },
  {
    id: "floor_press",
    name: "Dumbbell Floor Press",
    equipment: [Equipment.Dumbbell],
    primaryMuscles: [Muscle.Chest, Muscle.Triceps],
    secondaryMuscles: [Muscle.Shoulders],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Spine],
    movementPatterns: [MovementPattern.Push],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Beginner,
    tags: ["supine"],
    loadType: LoadType.Weighted,
    defaultLoadMale: 50,
    defaultLoadFemale: 30,
    substitutions: ["push_up"],
  },
  {
    id: "dumbbell_snatch",
    name: "Dumbbell Snatch",
    equipment: [Equipment.Dumbbell],
    primaryMuscles: [Muscle.Shoulders, Muscle.Hamstrings],
    secondaryMuscles: [Muscle.Core, Muscle.Glutes],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Hinge, MovementPattern.Push],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Intermediate,
    tags: ["overhead", "unilateral"],
    loadType: LoadType.Weighted,
    defaultLoadMale: 50,
    defaultLoadFemale: 35,
    substitutions: ["kettlebell_snatch", "kettlebell_swing"],
  },
  {
    id: "dumbbell_clean",
    name: "Dumbbell Clean",
    equipment: [Equipment.Dumbbell],
    primaryMuscles: [Muscle.Hamstrings, Muscle.Glutes],
    secondaryMuscles: [Muscle.Shoulders, Muscle.Core],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Hinge],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Intermediate,
    tags: [],
    loadType: LoadType.Weighted,
    defaultLoadMale: 50,
    defaultLoadFemale: 35,
    substitutions: ["kettlebell_clean", "kettlebell_swing"],
  },
  {
    id: "dumbbell_thruster",
    name: "Dumbbell Thruster",
    equipment: [Equipment.Dumbbell],
    primaryMuscles: [Muscle.Quads, Muscle.Shoulders],
    secondaryMuscles: [Muscle.Glutes, Muscle.Core],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Squat, MovementPattern.Push],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Intermediate,
    tags: ["overhead"],
    loadType: LoadType.Weighted,
    defaultLoadMale: 50,
    defaultLoadFemale: 35,
    substitutions: ["goblet_squat", "air_squat"],
  },
  {
    id: "dumbbell_deadlift",
    name: "Dumbbell Deadlift",
    equipment: [Equipment.Dumbbell],
    primaryMuscles: [Muscle.Hamstrings, Muscle.Glutes],
    secondaryMuscles: [Muscle.LowerBack, Muscle.Quads],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Hinge],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Beginner,
    tags: [],
    loadType: LoadType.Weighted,
    defaultLoadMale: 50,
    defaultLoadFemale: 35,
    substitutions: ["kettlebell_deadlift"],
  },
  {
    id: "dumbbell_row",
    name: "Dumbbell Row",
    equipment: [Equipment.Dumbbell],
    primaryMuscles: [Muscle.Lats, Muscle.UpperBack],
    secondaryMuscles: [Muscle.Biceps, Muscle.Forearms],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Pull],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Beginner,
    tags: ["unilateral"],
    loadType: LoadType.Weighted,
    defaultLoadMale: 50,
    defaultLoadFemale: 30,
    substitutions: ["ring_row", "banded_pull_up"],
  },
  {
    id: "kettlebell_swing",
    name: "Kettlebell Swing",
    equipment: [Equipment.Kettlebell],
    primaryMuscles: [Muscle.Hamstrings, Muscle.Glutes],
    secondaryMuscles: [Muscle.Core, Muscle.Shoulders],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Hinge],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Beginner,
    tags: [],
    loadType: LoadType.Weighted,
    defaultLoadMale: 53,
    defaultLoadFemale: 35,
    substitutions: ["dumbbell_deadlift"],
  },
  {
    id: "kettlebell_clean",
    name: "Kettlebell Clean",
    equipment: [Equipment.Kettlebell],
    primaryMuscles: [Muscle.Hamstrings, Muscle.Glutes],
    secondaryMuscles: [Muscle.Shoulders, Muscle.Core],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Hinge],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Intermediate,
    tags: [],
    loadType: LoadType.Weighted,
    defaultLoadMale: 53,
    defaultLoadFemale: 35,
    substitutions: ["kettlebell_swing"],
  },
  {
    id: "kettlebell_snatch",
    name: "Kettlebell Snatch",
    equipment: [Equipment.Kettlebell],
    primaryMuscles: [Muscle.Shoulders, Muscle.Hamstrings],
    secondaryMuscles: [Muscle.Core, Muscle.Glutes],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Hinge, MovementPattern.Push],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Intermediate,
    tags: ["overhead", "unilateral"],
    loadType: LoadType.Weighted,
    defaultLoadMale: 53,
    defaultLoadFemale: 35,
    substitutions: ["kettlebell_swing", "dumbbell_snatch"],
  },
  {
    id: "kettlebell_deadlift",
    name: "Kettlebell Deadlift",
    equipment: [Equipment.Kettlebell],
    primaryMuscles: [Muscle.Hamstrings, Muscle.Glutes],
    secondaryMuscles: [Muscle.LowerBack, Muscle.Quads],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Hinge],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Beginner,
    tags: [],
    loadType: LoadType.Weighted,
    defaultLoadMale: 53,
    defaultLoadFemale: 35,
    substitutions: ["dumbbell_deadlift"],
  },
  {
    id: "kettlebell_thruster",
    name: "Kettlebell Thruster",
    equipment: [Equipment.Kettlebell],
    primaryMuscles: [Muscle.Quads, Muscle.Shoulders],
    secondaryMuscles: [Muscle.Glutes, Muscle.Core],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Squat, MovementPattern.Push],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Intermediate,
    tags: ["overhead"],
    loadType: LoadType.Weighted,
    defaultLoadMale: 53,
    defaultLoadFemale: 35,
    substitutions: ["goblet_squat", "air_squat"],
  },
  {
    id: "turkish_get_up",
    name: "Turkish Get-Up",
    equipment: [Equipment.Kettlebell],
    primaryMuscles: [Muscle.Shoulders, Muscle.Core],
    secondaryMuscles: [Muscle.Glutes, Muscle.Quads, Muscle.HipFlexors],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Push, MovementPattern.Core],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Advanced,
    tags: ["overhead", "high_skill", "unilateral"],
    loadType: LoadType.Weighted,
    defaultLoadMale: 53,
    defaultLoadFemale: 35,
    substitutions: ["dumbbell_press"],
  },
  {
    id: "wall_ball_shot",
    name: "Wall Ball Shot",
    equipment: [Equipment.WallBall],
    primaryMuscles: [Muscle.Quads, Muscle.Shoulders],
    secondaryMuscles: [Muscle.Glutes, Muscle.Core],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Squat, MovementPattern.Push],
    modality: Modality.Weightlifting,
    difficulty: DifficultyTier.Beginner,
    tags: [],
    loadType: LoadType.Weighted,
    defaultLoadMale: 20,
    defaultLoadFemale: 14,
    substitutions: ["dumbbell_thruster", "air_squat"],
  },

  // ─── GYMNASTICS / BODYWEIGHT ─────────────────────────────────────
  {
    id: "air_squat",
    name: "Air Squat",
    equipment: [Equipment.None],
    primaryMuscles: [Muscle.Quads, Muscle.Glutes],
    secondaryMuscles: [Muscle.Hamstrings],
    loadedJoints: [Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Squat],
    modality: Modality.Gymnastics,
    difficulty: DifficultyTier.Beginner,
    tags: [],
    loadType: LoadType.Bodyweight,
    substitutions: [],
  },
  {
    id: "push_up",
    name: "Push-Up",
    equipment: [Equipment.None],
    primaryMuscles: [Muscle.Chest, Muscle.Triceps],
    secondaryMuscles: [Muscle.Shoulders, Muscle.Core],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Spine],
    movementPatterns: [MovementPattern.Push],
    modality: Modality.Gymnastics,
    difficulty: DifficultyTier.Beginner,
    tags: ["prone"],
    loadType: LoadType.Bodyweight,
    substitutions: [],
  },
  {
    id: "handstand_push_up",
    name: "Handstand Push-Up",
    equipment: [Equipment.None],
    primaryMuscles: [Muscle.Shoulders, Muscle.Triceps],
    secondaryMuscles: [Muscle.Core, Muscle.UpperBack],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Spine, Joint.Neck],
    movementPatterns: [MovementPattern.Push],
    modality: Modality.Gymnastics,
    difficulty: DifficultyTier.Advanced,
    tags: ["inverted", "overhead", "high_skill"],
    loadType: LoadType.Bodyweight,
    substitutions: ["push_up", "dumbbell_press", "strict_press", "pike_push_up"],
  },
  {
    id: "pike_push_up",
    name: "Pike Push-Up",
    equipment: [Equipment.None],
    primaryMuscles: [Muscle.Shoulders, Muscle.Triceps],
    secondaryMuscles: [Muscle.Core],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Spine, Joint.Neck],
    movementPatterns: [MovementPattern.Push],
    modality: Modality.Gymnastics,
    difficulty: DifficultyTier.Intermediate,
    tags: [],
    loadType: LoadType.Bodyweight,
    substitutions: ["push_up", "dumbbell_press"],
  },
  {
    id: "pull_up",
    name: "Pull-Up",
    equipment: [Equipment.PullUpBar],
    primaryMuscles: [Muscle.Lats, Muscle.Biceps],
    secondaryMuscles: [Muscle.UpperBack, Muscle.Forearms, Muscle.Core],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Spine],
    movementPatterns: [MovementPattern.Pull],
    modality: Modality.Gymnastics,
    difficulty: DifficultyTier.Intermediate,
    tags: [],
    loadType: LoadType.Bodyweight,
    substitutions: ["ring_row", "banded_pull_up", "jumping_pull_up"],
  },
  {
    id: "kipping_pull_up",
    name: "Kipping Pull-Up",
    equipment: [Equipment.PullUpBar],
    primaryMuscles: [Muscle.Lats, Muscle.Shoulders],
    secondaryMuscles: [Muscle.Biceps, Muscle.Core, Muscle.HipFlexors],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Pull],
    modality: Modality.Gymnastics,
    difficulty: DifficultyTier.Intermediate,
    tags: ["kipping"],
    loadType: LoadType.Bodyweight,
    substitutions: ["ring_row", "banded_pull_up", "jumping_pull_up", "pull_up"],
  },
  {
    id: "chest_to_bar_pull_up",
    name: "Chest-to-Bar Pull-Up",
    equipment: [Equipment.PullUpBar],
    primaryMuscles: [Muscle.Lats, Muscle.Biceps],
    secondaryMuscles: [Muscle.UpperBack, Muscle.Shoulders],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Pull],
    modality: Modality.Gymnastics,
    difficulty: DifficultyTier.Advanced,
    tags: ["kipping", "high_skill"],
    loadType: LoadType.Bodyweight,
    substitutions: ["ring_row", "banded_pull_up", "pull_up", "kipping_pull_up"],
  },
  {
    id: "muscle_up_bar",
    name: "Bar Muscle-Up",
    equipment: [Equipment.PullUpBar],
    primaryMuscles: [Muscle.Lats, Muscle.Chest, Muscle.Triceps],
    secondaryMuscles: [Muscle.Shoulders, Muscle.Core],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Pull, MovementPattern.Push],
    modality: Modality.Gymnastics,
    difficulty: DifficultyTier.RxPlus,
    tags: ["kipping", "high_skill"],
    loadType: LoadType.Bodyweight,
    substitutions: ["pull_up", "chest_to_bar_pull_up", "burpee_pull_up"],
  },
  {
    id: "muscle_up_ring",
    name: "Ring Muscle-Up",
    equipment: [Equipment.Rings],
    primaryMuscles: [Muscle.Lats, Muscle.Chest, Muscle.Triceps],
    secondaryMuscles: [Muscle.Shoulders, Muscle.Core],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Pull, MovementPattern.Push],
    modality: Modality.Gymnastics,
    difficulty: DifficultyTier.RxPlus,
    tags: ["kipping", "high_skill"],
    loadType: LoadType.Bodyweight,
    substitutions: ["pull_up", "ring_dip", "chest_to_bar_pull_up"],
  },
  {
    id: "ring_row",
    name: "Ring Row",
    equipment: [Equipment.Rings],
    primaryMuscles: [Muscle.UpperBack, Muscle.Biceps],
    secondaryMuscles: [Muscle.Lats, Muscle.Core],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Spine],
    movementPatterns: [MovementPattern.Pull],
    modality: Modality.Gymnastics,
    difficulty: DifficultyTier.Beginner,
    tags: [],
    loadType: LoadType.Bodyweight,
    substitutions: ["dumbbell_row"],
  },
  {
    id: "banded_pull_up",
    name: "Banded Pull-Up",
    equipment: [Equipment.PullUpBar, Equipment.ResistanceBand],
    primaryMuscles: [Muscle.Lats, Muscle.Biceps],
    secondaryMuscles: [Muscle.UpperBack],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Spine],
    movementPatterns: [MovementPattern.Pull],
    modality: Modality.Gymnastics,
    difficulty: DifficultyTier.Beginner,
    tags: [],
    loadType: LoadType.Bodyweight,
    substitutions: ["ring_row", "jumping_pull_up"],
  },
  {
    id: "jumping_pull_up",
    name: "Jumping Pull-Up",
    equipment: [Equipment.PullUpBar],
    primaryMuscles: [Muscle.Lats, Muscle.Biceps],
    secondaryMuscles: [Muscle.Quads],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Pull],
    modality: Modality.Gymnastics,
    difficulty: DifficultyTier.Beginner,
    tags: [],
    loadType: LoadType.Bodyweight,
    substitutions: ["ring_row"],
  },
  {
    id: "ring_dip",
    name: "Ring Dip",
    equipment: [Equipment.Rings],
    primaryMuscles: [Muscle.Chest, Muscle.Triceps],
    secondaryMuscles: [Muscle.Shoulders],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Spine],
    movementPatterns: [MovementPattern.Push],
    modality: Modality.Gymnastics,
    difficulty: DifficultyTier.Advanced,
    tags: [],
    loadType: LoadType.Bodyweight,
    substitutions: ["push_up", "dumbbell_bench_press"],
  },
  {
    id: "toes_to_bar",
    name: "Toes-to-Bar",
    equipment: [Equipment.PullUpBar],
    primaryMuscles: [Muscle.Core, Muscle.HipFlexors],
    secondaryMuscles: [Muscle.Lats, Muscle.Forearms],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Core],
    modality: Modality.Gymnastics,
    difficulty: DifficultyTier.Intermediate,
    tags: ["kipping"],
    loadType: LoadType.Bodyweight,
    substitutions: ["hanging_knee_raise", "v_up", "sit_up"],
  },
  {
    id: "knees_to_elbow",
    name: "Knees-to-Elbow",
    equipment: [Equipment.PullUpBar],
    primaryMuscles: [Muscle.Core, Muscle.HipFlexors],
    secondaryMuscles: [Muscle.Forearms],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Core],
    modality: Modality.Gymnastics,
    difficulty: DifficultyTier.Intermediate,
    tags: ["kipping"],
    loadType: LoadType.Bodyweight,
    substitutions: ["hanging_knee_raise", "sit_up"],
  },
  {
    id: "hanging_knee_raise",
    name: "Hanging Knee Raise",
    equipment: [Equipment.PullUpBar],
    primaryMuscles: [Muscle.Core, Muscle.HipFlexors],
    secondaryMuscles: [Muscle.Forearms],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Core],
    modality: Modality.Gymnastics,
    difficulty: DifficultyTier.Beginner,
    tags: [],
    loadType: LoadType.Bodyweight,
    substitutions: ["sit_up", "v_up"],
  },
  {
    id: "sit_up",
    name: "Sit-Up",
    equipment: [Equipment.None],
    primaryMuscles: [Muscle.Core],
    secondaryMuscles: [Muscle.HipFlexors],
    loadedJoints: [Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Core],
    modality: Modality.Gymnastics,
    difficulty: DifficultyTier.Beginner,
    tags: ["supine"],
    loadType: LoadType.Bodyweight,
    substitutions: [],
  },
  {
    id: "v_up",
    name: "V-Up",
    equipment: [Equipment.None],
    primaryMuscles: [Muscle.Core],
    secondaryMuscles: [Muscle.HipFlexors],
    loadedJoints: [Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Core],
    modality: Modality.Gymnastics,
    difficulty: DifficultyTier.Intermediate,
    tags: ["supine"],
    loadType: LoadType.Bodyweight,
    substitutions: ["sit_up"],
  },
  {
    id: "ghd_sit_up",
    name: "GHD Sit-Up",
    equipment: [Equipment.GHD],
    primaryMuscles: [Muscle.Core, Muscle.HipFlexors],
    secondaryMuscles: [Muscle.LowerBack],
    loadedJoints: [Joint.Knees, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Core],
    modality: Modality.Gymnastics,
    difficulty: DifficultyTier.Intermediate,
    tags: [],
    loadType: LoadType.Bodyweight,
    substitutions: ["sit_up", "v_up"],
  },
  {
    id: "back_extension",
    name: "Back Extension",
    equipment: [Equipment.GHD],
    primaryMuscles: [Muscle.LowerBack, Muscle.Glutes],
    secondaryMuscles: [Muscle.Hamstrings],
    loadedJoints: [Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Hinge],
    modality: Modality.Gymnastics,
    difficulty: DifficultyTier.Beginner,
    tags: ["prone"],
    loadType: LoadType.Bodyweight,
    substitutions: ["deadlift", "kettlebell_swing"],
  },
  {
    id: "burpee",
    name: "Burpee",
    equipment: [Equipment.None],
    primaryMuscles: [Muscle.Chest, Muscle.Quads],
    secondaryMuscles: [Muscle.Shoulders, Muscle.Core, Muscle.HipFlexors],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Push, MovementPattern.Squat],
    modality: Modality.Gymnastics,
    difficulty: DifficultyTier.Beginner,
    tags: ["high_impact", "prone"],
    loadType: LoadType.Bodyweight,
    substitutions: ["air_squat"],
  },
  {
    id: "burpee_pull_up",
    name: "Burpee Pull-Up",
    equipment: [Equipment.PullUpBar],
    primaryMuscles: [Muscle.Chest, Muscle.Lats],
    secondaryMuscles: [Muscle.Shoulders, Muscle.Core, Muscle.Quads],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Push, MovementPattern.Pull],
    modality: Modality.Gymnastics,
    difficulty: DifficultyTier.Intermediate,
    tags: ["high_impact", "prone"],
    loadType: LoadType.Bodyweight,
    substitutions: ["burpee", "pull_up"],
  },
  {
    id: "box_jump",
    name: "Box Jump",
    equipment: [Equipment.Box],
    primaryMuscles: [Muscle.Quads, Muscle.Calves],
    secondaryMuscles: [Muscle.Glutes, Muscle.HipFlexors],
    loadedJoints: [Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Squat],
    modality: Modality.Gymnastics,
    difficulty: DifficultyTier.Intermediate,
    tags: ["high_impact", "plyometric"],
    loadType: LoadType.Bodyweight,
    substitutions: ["box_step_up", "air_squat"],
  },
  {
    id: "box_step_up",
    name: "Box Step-Up",
    equipment: [Equipment.Box],
    primaryMuscles: [Muscle.Quads, Muscle.Glutes],
    secondaryMuscles: [Muscle.Calves],
    loadedJoints: [Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Squat],
    modality: Modality.Gymnastics,
    difficulty: DifficultyTier.Beginner,
    tags: ["unilateral"],
    loadType: LoadType.Bodyweight,
    substitutions: ["air_squat", "lunge"],
  },
  {
    id: "lunge",
    name: "Lunge",
    equipment: [Equipment.None],
    primaryMuscles: [Muscle.Quads, Muscle.Glutes],
    secondaryMuscles: [Muscle.Hamstrings, Muscle.Core],
    loadedJoints: [Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Squat],
    modality: Modality.Gymnastics,
    difficulty: DifficultyTier.Beginner,
    tags: ["unilateral"],
    loadType: LoadType.Bodyweight,
    substitutions: ["air_squat"],
  },
  {
    id: "walking_lunge",
    name: "Walking Lunge",
    equipment: [Equipment.None],
    primaryMuscles: [Muscle.Quads, Muscle.Glutes],
    secondaryMuscles: [Muscle.Hamstrings, Muscle.Core],
    loadedJoints: [Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Squat],
    modality: Modality.Gymnastics,
    difficulty: DifficultyTier.Beginner,
    tags: ["unilateral"],
    loadType: LoadType.Bodyweight,
    substitutions: ["lunge", "air_squat"],
  },
  {
    id: "pistol_squat",
    name: "Pistol Squat",
    equipment: [Equipment.None],
    primaryMuscles: [Muscle.Quads, Muscle.Glutes],
    secondaryMuscles: [Muscle.Core],
    loadedJoints: [Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Squat],
    modality: Modality.Gymnastics,
    difficulty: DifficultyTier.Advanced,
    tags: ["unilateral", "high_skill"],
    loadType: LoadType.Bodyweight,
    substitutions: ["air_squat", "lunge", "box_step_up"],
  },
  {
    id: "handstand_walk",
    name: "Handstand Walk",
    equipment: [Equipment.None],
    primaryMuscles: [Muscle.Shoulders, Muscle.Core],
    secondaryMuscles: [Muscle.Triceps],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Spine, Joint.Neck],
    movementPatterns: [MovementPattern.Push, MovementPattern.Core],
    modality: Modality.Gymnastics,
    difficulty: DifficultyTier.RxPlus,
    tags: ["inverted", "high_skill"],
    loadType: LoadType.Distance,
    substitutions: ["bear_crawl", "dumbbell_press"],
  },
  {
    id: "bear_crawl",
    name: "Bear Crawl",
    equipment: [Equipment.None],
    primaryMuscles: [Muscle.Shoulders, Muscle.Core],
    secondaryMuscles: [Muscle.Quads, Muscle.Triceps],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Push, MovementPattern.Core],
    modality: Modality.Gymnastics,
    difficulty: DifficultyTier.Beginner,
    tags: ["prone"],
    loadType: LoadType.Distance,
    substitutions: [],
  },
  {
    id: "rope_climb",
    name: "Rope Climb",
    equipment: [Equipment.Rope],
    primaryMuscles: [Muscle.Lats, Muscle.Biceps],
    secondaryMuscles: [Muscle.Forearms, Muscle.Core],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Pull],
    modality: Modality.Gymnastics,
    difficulty: DifficultyTier.Advanced,
    tags: ["high_skill"],
    loadType: LoadType.Bodyweight,
    substitutions: ["pull_up", "ring_row"],
  },
  {
    id: "plank",
    name: "Plank Hold",
    equipment: [Equipment.None],
    primaryMuscles: [Muscle.Core],
    secondaryMuscles: [Muscle.Shoulders],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Spine],
    movementPatterns: [MovementPattern.Core],
    modality: Modality.Gymnastics,
    difficulty: DifficultyTier.Beginner,
    tags: ["isometric", "prone"],
    loadType: LoadType.Duration,
    substitutions: [],
  },

  // ─── MONOSTRUCTURAL / CARDIO ─────────────────────────────────────
  {
    id: "run",
    name: "Run",
    equipment: [Equipment.None],
    primaryMuscles: [Muscle.Quads, Muscle.Calves],
    secondaryMuscles: [Muscle.Hamstrings, Muscle.Glutes, Muscle.Core],
    loadedJoints: [Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Squat],
    modality: Modality.Monostructural,
    difficulty: DifficultyTier.Beginner,
    tags: ["high_impact"],
    loadType: LoadType.Distance,
    substitutions: ["row", "bike_erg", "assault_bike"],
  },
  {
    id: "row",
    name: "Row",
    equipment: [Equipment.Rower],
    primaryMuscles: [Muscle.Hamstrings, Muscle.UpperBack],
    secondaryMuscles: [Muscle.Quads, Muscle.Biceps, Muscle.Core],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Pull, MovementPattern.Hinge],
    modality: Modality.Monostructural,
    difficulty: DifficultyTier.Beginner,
    tags: [],
    loadType: LoadType.Calories,
    substitutions: ["run", "bike_erg", "assault_bike"],
  },
  {
    id: "bike_erg",
    name: "Bike Erg",
    equipment: [Equipment.BikeErg],
    primaryMuscles: [Muscle.Quads, Muscle.Calves],
    secondaryMuscles: [Muscle.Hamstrings, Muscle.Glutes],
    loadedJoints: [Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Squat],
    modality: Modality.Monostructural,
    difficulty: DifficultyTier.Beginner,
    tags: [],
    loadType: LoadType.Calories,
    substitutions: ["run", "row", "assault_bike"],
  },
  {
    id: "assault_bike",
    name: "Assault Bike",
    equipment: [Equipment.AssaultBike],
    primaryMuscles: [Muscle.Quads],
    secondaryMuscles: [Muscle.Shoulders, Muscle.Hamstrings, Muscle.Core],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Squat],
    modality: Modality.Monostructural,
    difficulty: DifficultyTier.Beginner,
    tags: [],
    loadType: LoadType.Calories,
    substitutions: ["run", "row", "bike_erg"],
  },
  {
    id: "ski_erg",
    name: "Ski Erg",
    equipment: [Equipment.SkiErg],
    primaryMuscles: [Muscle.Lats, Muscle.Core],
    secondaryMuscles: [Muscle.Triceps, Muscle.Shoulders],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Pull],
    modality: Modality.Monostructural,
    difficulty: DifficultyTier.Beginner,
    tags: [],
    loadType: LoadType.Calories,
    substitutions: ["row", "assault_bike"],
  },
  {
    id: "double_under",
    name: "Double-Under",
    equipment: [Equipment.JumpRope],
    primaryMuscles: [Muscle.Calves],
    secondaryMuscles: [Muscle.Shoulders, Muscle.Forearms],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Squat],
    modality: Modality.Monostructural,
    difficulty: DifficultyTier.Intermediate,
    tags: ["high_impact", "high_skill"],
    loadType: LoadType.Bodyweight,
    substitutions: ["single_under"],
  },
  {
    id: "single_under",
    name: "Single-Under",
    equipment: [Equipment.JumpRope],
    primaryMuscles: [Muscle.Calves],
    secondaryMuscles: [Muscle.Shoulders],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Squat],
    modality: Modality.Monostructural,
    difficulty: DifficultyTier.Beginner,
    tags: ["high_impact"],
    loadType: LoadType.Bodyweight,
    substitutions: [],
  },

  // ─── STRONGMAN ───────────────────────────────────────────────────
  {
    id: "sled_push",
    name: "Sled Push",
    equipment: [Equipment.Sled],
    primaryMuscles: [Muscle.Quads, Muscle.Glutes],
    secondaryMuscles: [Muscle.Calves, Muscle.Core, Muscle.Shoulders],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Squat, MovementPattern.Core],
    modality: Modality.Strongman,
    difficulty: DifficultyTier.Intermediate,
    tags: [],
    loadType: LoadType.Distance,
    substitutions: ["run", "air_squat"],
  },
  {
    id: "sled_pull",
    name: "Sled Pull",
    equipment: [Equipment.Sled],
    primaryMuscles: [Muscle.Hamstrings, Muscle.Glutes],
    secondaryMuscles: [Muscle.UpperBack, Muscle.Biceps],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Hinge, MovementPattern.Pull],
    modality: Modality.Strongman,
    difficulty: DifficultyTier.Intermediate,
    tags: [],
    loadType: LoadType.Distance,
    substitutions: ["row", "kettlebell_swing"],
  },
  {
    id: "sandbag_carry",
    name: "Sandbag Carry",
    equipment: [Equipment.Sandbag],
    primaryMuscles: [Muscle.Core, Muscle.Glutes],
    secondaryMuscles: [Muscle.Quads, Muscle.UpperBack, Muscle.Forearms],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Carry, MovementPattern.Core],
    modality: Modality.Strongman,
    difficulty: DifficultyTier.Intermediate,
    tags: ["axial_load"],
    loadType: LoadType.Distance,
    substitutions: ["run"],
  },
  {
    id: "farmers_carry",
    name: "Farmer's Carry",
    equipment: [Equipment.Dumbbell],
    primaryMuscles: [Muscle.Forearms, Muscle.Core],
    secondaryMuscles: [Muscle.Shoulders, Muscle.UpperBack],
    loadedJoints: [Joint.Wrists, Joint.Elbows, Joint.Knees, Joint.Ankles, Joint.Hips, Joint.Spine],
    movementPatterns: [MovementPattern.Carry, MovementPattern.Core],
    modality: Modality.Strongman,
    difficulty: DifficultyTier.Beginner,
    tags: [],
    loadType: LoadType.Distance,
    defaultLoadMale: 70,
    defaultLoadFemale: 45,
    substitutions: [],
  },
];

/** Index movements by ID for fast lookup */
const movementIndex = new Map<string, Movement>();
for (const m of MOVEMENT_LIBRARY) {
  movementIndex.set(m.id, m);
}

export function getMovement(id: string): Movement | undefined {
  return movementIndex.get(id);
}

export function getMovementOrThrow(id: string): Movement {
  const m = movementIndex.get(id);
  if (!m) throw new Error(`Movement not found: ${id}`);
  return m;
}

export function getAllMovements(): Movement[] {
  return [...MOVEMENT_LIBRARY];
}

export function getMovementsByModality(modality: Modality): Movement[] {
  return MOVEMENT_LIBRARY.filter((m) => m.modality === modality);
}

export function getMovementsByMovementPattern(group: MovementPattern): Movement[] {
  return MOVEMENT_LIBRARY.filter((m) => m.movementPatterns.includes(group));
}

export function getMovementsByEquipment(equipment: Equipment[]): Movement[] {
  const available = new Set(equipment);
  return MOVEMENT_LIBRARY.filter((m) =>
    m.equipment.every((e) => e === Equipment.None || available.has(e))
  );
}
